site_name: NDD docs
nav:
  - Home: index.md
  - Quick start: 
    - Install ndd: start/install.md
    - Provision a network device: start/provision.md
    - Uninstall ndd: start/uninstall.md
  - Examples: examples/examples.md
  - Concepts:
    - Architecture: concepts/architecture.md
    - Providers: concepts/provider.md
    - Managed Resource: concepts/resource.md
    - Packages: concepts/package.md
    - Terminology: concepts/terminology.md
  - API documentation: 
    - overview: api/overview.md
    - ndd-core: https://doc.crds.dev/github.com/yndd/ndd-core
    - ndd-provider-srl: https://doc.crds.dev/github.com/yndd/ndd-provider-srl
  - FAQ: faq/faq.md
  - Community: community/community.md
        
site_author: Wim Henderickx
site_description: >-
  NDD enables platform and application teams to consume network devices through the kubernetes api
# repository
repo_name: yndd/ndddocs
repo_url: https://github.com/yndd/ndddocs
site_url: "https://ndd.yndd.io"
edit_uri: ""
theme:
  name: material
  custom_dir: docs/overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    #- content.code.annotate
    #- content.tabs.link
    # - header.autohide
    # - navigation.expand
    # - navigation.indexes
    # - navigation.instant
    #- navigation.sections
    #- navigation.tabs
    # - navigation.tabs.sticky
    #- navigation.top
    #- navigation.tracking
    #- search.highlight
    #- search.share
    #- search.suggest
    # - toc.integrate
    
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Manrope
    code: Fira Mono
  icon:
    logo: fontawesome/solid/flask   
  #favicon: images/srl.png

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  
# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yndd
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/whenderickx
    - icon: fontawesome/brands/discord
      link: https://discord.gg/prHcBMSq
  analytics:
    provider: google
    property: G-368XR9X5MG
    
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde